### PR TITLE
update to current version of the savefile and switch to sqlite

### PR DESCRIPTION
**Pull request by Alien-AV**
fixed a few issues that failed conversion of my own save

### CODE REVIEW

**Comment by Darokrithia** [comment]
Wow, ck2 updated a while ago (Nearly a year ago yikes) and it broke some of the parsing on newer saves.  I've been meaning to fix this for a while, so thank you so much for doing this!  I will review this and then merge it in

**Comment by Alien-AV** [comment]
Didn't realize it would get added to the same pull request, but I guess it's no big deal. I can remove/fix either part if you'll have issues with it.

**Comment by Darokrithia** [comment]
No, it is fine.  Thanks again for contributing!

**Comment by Darokrithia** [comment]
Going over this now

**Comment by Darokrithia** [comment]
It looks like this will get us around the dict issue https://stackoverflow.com/questions/3300464/how-can-i-get-dict-from-sqlite-query

**Comment by Darokrithia** [comment]
Wait you already linked that haha 🤦 my b

**Comment by Darokrithia** [comment]
So on lines 84-87 of get dynasty I could only get the code to run if I changed it from
`                       if name != None: cur.execute('UPDATE dynasty SET dynastyname=? WHERE dynastyID=?',[name])`
`			if cultureID != None: cur.execute('UPDATE dynasty SET dynastyname=? WHERE dynastyID=?',[cultureID])`
`			if religionID != None: cur.execute('UPDATE dynasty SET dynastyname=? WHERE dynastyID=?',[religionID])`

to
`			if name != None: cur.execute('UPDATE dynasty SET dynastyname=? WHERE dynastyID=?',[name, name])`
`			if cultureID != None: cur.execute('UPDATE dynasty SET dynastyname=? WHERE dynastyID=?',[cultureID, cultureID])`
`			if religionID != None: cur.execute('UPDATE dynasty SET dynastyname=? WHERE dynastyID=?',[religionID, religionID])`

So I think we should fix that before I merge the changes in @Alien-AV 

Related: @OwenDurkin @nfusionz What is the point of those lines?  I kind of have forgotten hahaha.  It seems to be setting the dynasty name and ID's to the religions / names / cultures of characters.  IIRC we had a fall back that would name unnamed dynasties, but this doesn't seem to be hitting unnamed dynasties, and if it was that I would think the last to ifs would be elifs.

Thanks!

**Comment by Darokrithia** [comment]
To clarify everything else looks good and I am otherwise ready to merge :)

**Pull request merged**
